"""Tier A (§13) — pure core, no bpy.

Golden fixtures: sedan, SUV, van, and a badly-named car where every
object is Cube.0NN. Assert roles. Fixtures are generated by
car_fixture_builder.py (see tests/fixtures/*.json) — geometry only, no
name signal except badly_named.json's deliberately-absent one, so a
passing test_badly_named proves classification is geometry-driven.
"""
from crash_forge.core.classify import PartRole, classify, detect_forward_axis

from .car_fixture_builder import load_fixture

EXPECTED_ROLES_BY_SUFFIX = {
    "Body": PartRole.BODY,
    "Wheel_FL": PartRole.WHEEL_FL,
    "Wheel_FR": PartRole.WHEEL_FR,
    "Wheel_RL": PartRole.WHEEL_RL,
    "Wheel_RR": PartRole.WHEEL_RR,
    "Hood": PartRole.HOOD,
    "Boot": PartRole.BOOT,
    "Bumper_F": PartRole.BUMPER_F,
    "Bumper_R": PartRole.BUMPER_R,
    "Door_L": PartRole.DOOR_L,
    "Door_R": PartRole.DOOR_R,
    "Glass_Windshield": PartRole.GLASS,
    "Glass_Rear": PartRole.GLASS,
}


def _assert_all_roles_correct(parts, name_to_expected_role):
    forward_axis = detect_forward_axis(parts)
    result = classify(parts, forward_axis)
    assert set(result.keys()) == {p.name for p in parts}
    for part in parts:
        expected = name_to_expected_role[part.name]
        actual = result[part.name].role
        assert actual == expected, f"{part.name}: expected {expected}, got {actual}"
        assert 0.0 <= result[part.name].confidence <= 1.0


def test_sedan_classifies_every_part_correctly():
    parts = load_fixture("sedan")
    _assert_all_roles_correct(parts, EXPECTED_ROLES_BY_SUFFIX)


def test_suv_classifies_every_part_correctly():
    parts = load_fixture("suv")
    _assert_all_roles_correct(parts, EXPECTED_ROLES_BY_SUFFIX)


def test_van_classifies_every_part_correctly():
    parts = load_fixture("van")
    _assert_all_roles_correct(parts, EXPECTED_ROLES_BY_SUFFIX)


def test_badly_named_car_still_classifies_correctly_by_geometry_alone():
    """Every object is Cube.0NN — the same geometry as the sedan fixture,
    built in the same part order, so index position maps 1:1 back to the
    role that name would have had. If this passes, classification is
    provably geometry-driven, not name-driven (§12.1: "verify against
    geometry — never trust a name alone")."""
    parts = load_fixture("badly_named")
    ordered_expected = list(EXPECTED_ROLES_BY_SUFFIX.values())
    assert len(parts) == len(ordered_expected)

    forward_axis = detect_forward_axis(parts)
    result = classify(parts, forward_axis)

    for part, expected_role in zip(parts, ordered_expected):
        actual = result[part.name].role
        assert actual == expected_role, f"{part.name}: expected {expected_role}, got {actual}"


def test_badly_named_hood_confidence_is_not_boosted_by_a_name_hint():
    """The sedan's real "Hood" part gets a +0.15 name-hint confidence
    boost (name matches geometry's call); Cube.005 (same part,
    geometrically) must not, since there's no name signal to agree with."""
    sedan = load_fixture("sedan")
    badly_named = load_fixture("badly_named")

    sedan_result = classify(sedan, detect_forward_axis(sedan))
    badly_named_result = classify(badly_named, detect_forward_axis(badly_named))

    sedan_hood_conf = sedan_result["Hood"].confidence
    badly_named_hood_conf = badly_named_result["Cube.005"].confidence

    assert sedan_hood_conf > badly_named_hood_conf


def test_name_hint_never_overrides_a_disagreeing_geometric_call():
    """A part named "door" whose geometry doesn't look like a door at all
    (placed and shaped like a bumper) must classify by geometry — the
    keyword only nudges confidence when it *agrees* (§12.1 step 5)."""
    from crash_forge.core.classify import PartDescriptor

    parts = load_fixture("sedan")
    # Rename the front bumper to something with a misleading "door" keyword.
    renamed = []
    for p in parts:
        if p.name == "Bumper_F":
            renamed.append(PartDescriptor(
                name="door_mislabeled", bbox_min=p.bbox_min, bbox_max=p.bbox_max, centroid=p.centroid,
                vert_count=p.vert_count, material_names=p.material_names,
                max_transmission=p.max_transmission, is_planar=p.is_planar,
            ))
        else:
            renamed.append(p)

    result = classify(renamed, detect_forward_axis(renamed))
    assert result["door_mislabeled"].role == PartRole.BUMPER_F
